### ISSUE TITLE
I have a 601 logger but i cant get it working

### ISSUE THREAD

**Issue by Ironburn** [wouterbaake/OmnikMQTT#2]
sorry for my bad English,
I have a 601 data logger. But how do I install this script? I am new to this world. But it is very frustrating that I don't get it working. Or do I miss the manual? Or would I recommend another data logger (UTP not WIFI)

**Comment by wouterbaake** [comment]
I have updated the README slightly to give more instructions. However, if you are unfamiliar with Python and IPtables this will be a difficult project to get started with.
